site_name: mkdocs sample
site_url: https://www.google.com/
repo_url: https://github.com/shibataka000/mkdocs-sample
repo_name: mkdocs-sample
site_description: site description
copyright: copyright
site_author: shibataka000
nav:
  - Home: index.md
  - Policies:
      - "1": policies/1.md
      - "2": policies/2.md
      - "3": policies/3.md
  - Guideline:
      - phase-1:
          - task-1:
              - item-1: guidelines/phase-1/task-1/アイテム1.md
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
# strict: true
