name: Release
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
      - run: uv run mkdocs build
      - uses: actions/upload-artifact@v4
        with:
          name: document.pdf
          path: ./site/pdf/document.pdf
      # - name: Create release
      #   run: gh release create "${TAG}" ./site/pdf/document.pdf --generate-notes
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TAG: ${{ github.ref_name }}
